README.md, src/main/java/com/microsoft/graph/concurrency/DefaultExecutors.java, src/main/java/com/microsoft/graph/core/DefaultClientConfig.java, src/main/java/com/microsoft/graph/http/DefaultHttpProvider.java, src/main/java/com/microsoft/graph/requests/extensions/GraphServiceClient.java, src/main/java/com/microsoft/graph/serializer/DefaultSerializer.java, src/test/java/com/microsoft/graph/core/DefaultClientConfigTests.java, src/test/java/com/microsoft/graph/functional/TestBase.java, src/test/java/com/microsoft/graph/requests/extensions/GraphServiceClientTest.java
See #40 
The crux of this PR is it supports this use of `GraphServiceClient`:
```java
client = GraphServiceClient.fromConfig(config);
```
and
```java
client = GraphServiceClient
.builder()
.logger(logger)
.executors(executors)
...
.buildClient();
```
It is not possible to override sensibly the behaviour of an instantiated config because it can only be overriden via inheritance.  For this reason the static factory method `fromConfig` returns a client straight away rather than allowing further builder modification.
The builder path is based on `DefaultClientConfig` and allows any of the bits below to be overriden in a sensible way. That is if I override the logger then it will be used in all the components.
*UML Dependency diagram - DefaultClientConfig*
A quick note that there are more …
=> rework GraphServiceClient

src/main/java/com/microsoft/graph/models/extensions/Multipart.java, src/main/java/com/microsoft/graph/models/extensions/PlannerAssignment.java, src/main/java/com/microsoft/graph/models/extensions/PlannerBucket.java, src/main/java/com/microsoft/graph/models/extensions/PlannerChecklistItem.java, src/main/java/com/microsoft/graph/models/extensions/PlannerExternalReference.java, src/main/java/com/microsoft/graph/models/extensions/PlannerTask.java, src/main/java/com/microsoft/graph/models/extensions/PlannerTaskDetails.java, src/test/java/com/microsoft/graph/functional/OneNoteTests.java, src/test/java/com/microsoft/graph/functional/PlannerTests.java
[12f6b8e](https://github.com/microsoftgraph/msgraph-sdk-java/commit/12f6b8e95c0963b61bcf28a5732f333e8e96a55d) - Add helper for multipart header and update OneNote multipart test to use header
[88f0cb6](https://github.com/microsoftgraph/msgraph-sdk-java/commit/88f0cb63bfe74c470af054296b1bcad6a16f3397) - Add default @odata.type parameters for Planner models, so the user does not need to specify them herself
=> Workload helper updates

src/test/java/com/microsoft/graph/serializer/AdditionalDataTests.java
Fix: Changed the string against which unit testing is being done. There is a odataType string member variable in Base class, which is overriden in one of the class which is being serialized. Hence @odata.type string should also be present in the serialized string for the object.
Fixes #
-
-
=> Issue: Hashmap child annotation serialization unit test failing

gradle.properties
as per title. 10GB works for linux.
Is the memory requirement larger on Windows?
=> increase gradle heap requirement to 11GB

build.gradle, gradle.properties
This PR fixes  these things about publishing maven artifacts:
* the suffix (-SNAPSHOT) should be an optional part of the version and should be present in the dev branch always
* the publish section in build.gradle did not work because property substitution does not occur in single quotes. Needs double quotes.
* the publish section did not pick up the patch version
=> fix published artifact versions

gradle.properties
We can now drop the memory requirement to 2GB in gradle.properties for runnning the build thanks to @deepak2016 recent merged PR #125.
=> reduce memory requirement for gradle to 2g 

src/main/java/com/microsoft/graph/models/extensions/Multipart.java, src/test/java/com/microsoft/graph/functional/OneNoteTests.java, src/test/java/com/microsoft/graph/http/MockConnection.java, src/test/java/com/microsoft/graph/models/extensions/MultipartTests.java
Fixes #105 
- Set getbytes in Multipart to US-ASCII.
- Set getbytes in jsonResponse to UTF-8.
- Added getter and setter for boundary and  Content-Type of Multipart.
- Removed function addPart(String name, String contentType, String content).
- Renamed function addPart(String name, String contentType, byte[] byteArray) To addFormData(String name, String contentType, byte[] byteArray).
- Added function addPart(Map<String, String> headers, byte[] content) for user provided headers and byte content.
-https://tools.ietf.org/html/rfc7578
=> Getbytes encoding fix

build.gradle
Using "gradle generatePomFileForMavenPublication" to generate pom file in build\libs.
=> pom generation to build\libs.

build.gradle, gradle.properties
Changes proposed in this pull request
- Renamed mavenJava task to mavenCentralRelease for readability.
- Added separate task for mavenCentralSnapshot publishing.
- Restructured code in build.gradle and gradle.properties for build automation pipeline.
Now we can publish to mavenCentral's snapshot and release using 
- gradle publishMavenCentralSnapshotPublicationToMavenRepository
- gradle publishMavenCentralReleasePublicationToMaven2Repository
=> Gradle publish tasks modification

build.gradle
- Checking credential keys to be used is present in local.properties and then apply toLowerCase() and toBoolean() to it.
=> Checks credential key to be used from local.properties.

src/main/java/com/microsoft/graph/core/DefaultConnectionConfig.java, src/main/java/com/microsoft/graph/core/IConnectionConfig.java, src/main/java/com/microsoft/graph/http/DefaultHttpProvider.java, src/main/java/com/microsoft/graph/http/IConnection.java, src/main/java/com/microsoft/graph/http/IHttpProvider.java, src/main/java/com/microsoft/graph/http/UrlConnection.java, src/test/java/com/microsoft/graph/http/MockConnection.java, src/test/java/com/microsoft/graph/http/MockHttpProvider.java, src/test/java/com/microsoft/graph/requests/extensions/GraphServiceClientTest.java
Fixes #196 
- Added DefaultConnectionConfig which implement IConnectionConfig. Any class implementing IConnectionConfig can be passed with configured timeout values.
- Added setter and getter functions for changing values timeout values in DefaultHttpProvider.
=> Configure connection timeout

src/main/java/com/microsoft/graph/http/CoreHttpProvider.java
Fixes #270
-During a POST request, if the body was empty, then it showed NullPointerException. 
Redefined contenttype value for this case.
=> fixed NullpointerException in content type during post call

.azure-pipelines/generate-v1.0-models.yml, .github/workflows/create-v1.0-pull-request.yml
Generates models and request builders, disables CI for manual runs (so we no longer have to get notifications when creating/debugging pipelines)
Used to generate https://github.com/microsoftgraph/msgraph-sdk-java/pull/352
=> Add yaml generation pipeline for v1.0 typings

src/main/java/com/microsoft/graph/serializer/DefaultSerializer.java, src/test/java/com/microsoft/graph/serializer/AdditionalDataTests.java
Fixes #374 
-Code snippet:
DriveItem driveItem = new DriveItem();
driveItem.name = folder;
driveItem.folder = new Folder();
driveItem.folder.additionalDataManager().put("@microsoft.graph.conflictBehavior", new JsonPrimitive("rename"));
The additionalDataManager content will not add in request payload because of transient type.
Actual payload : {"folder":{},"name":"folder"}
Expected payload: {"folder":{},"name":"folder", "@microsoft.graph.conflictBehavior":"rename"}
In DefaultSerializer.java file, the method fieldIsOdataTransient() not considering the "@microsoft.graph.conflictBehavior" entry.
Added check for "@microsoft.graph.conflictBehavior" entry same as "@odata.type" entry.
-
=> Fix issue #374 driveItem.additionalDataManager().put() not working

src/main/java/com/microsoft/graph/http/CoreHttpProvider.java, src/main/java/com/microsoft/graph/http/GraphServiceException.java
Fixes #284 
Closes #333
- OkHttp response bodies are required to be closed. See https://square.github.io/okhttp/4.x/okhttp/okhttp3/-response-body/. There are a couple of places in which this does not happen, and this pull should fix at least some of those leaks.
The first is in `CoreHttpProvider`. In the cases in which a `byteStream` is obtained from the response body, the stream is closed, which closes the body, so those are ok. However, in some other cases, the Response is used without closing it. Now, closing the Response in the finally method covers all those situations.
The second is in `GraphServiceException` which reads the response body but did not close it.
- https://square.github.io/okhttp/4.x/okhttp/okhttp3/-response-body/
=> Fix some OkHttp response body leaks

src/main/java/com/microsoft/graph/http/DefaultHttpProvider.java
This allows custom a ConnectionFactory to be passed in.
DefaultHttpProvider is useful, but I need to pass in a different IConnectionFactory for my use case.
I know I could always rewrite DefaultHttpProvider to use a custom connection factory, but this might be useful to others.
#367
=> Add second constructor to DefaultHttpProvider

src/main/java/com/microsoft/graph/concurrency/ChunkedUploadProvider.java
Fixes #396 
- Continue to read from the input stream to make sure the buffer is filled with data until the chunk size is reached before executing the chunked upload request.
=> [#396] OneDrive Chunked Upload - Chunk size is not taken into consideration in case of customized input stream

src/main/java/com/microsoft/graph/http/GraphServiceException.java
Fixes #387
- error messages look like this instead of containing the JWT
```
PUT https://graph.microsoft.com/v1.0/groups/263746d9-2294-4506-87c4-7d4a50d81332/team
SdkVersion : graph-java/v2.0.0
Authorization : [PII_REDACTED]
{"funSettings":{"allowCustomMemes":false},"memberS[...]
```
-
=> - fixes a bug where jwts would be shown in error messages

src/main/java/com/microsoft/graph/http/GraphServiceException.java
=> - adds getters to the graph service exception for better introspection

src/main/java/com/microsoft/graph/http/CoreHttpProvider.java, src/test/java/com/microsoft/graph/functional/UserTests.java
Fixes #357 
Warning: this pull request contains #463 to ease up the writing of the unit test. 463 should be reviewed and merged first.
-
-
=> - fixes a bug where the content type of a post request would be forcibly overridden

.gitignore, src/main/java/com/microsoft/graph/serializer/DefaultSerializer.java, src/test/java/com/microsoft/graph/serializer/AdditionalDataTests.java
This PR tries to solve #511 issue.
I just modified the `getChildAdditionalData` method in order to support the serialization of additional properties on List items.
=> [issue-511] Fix serialization of additional data on Collections

.github/dependabot.yml
related #514
closes #518
The introduction of a placeholder pom for the dependency graph turned on dependabot for that dependencies manager. This PR disbales it
=> - disables dependabot for the pom/maven placeholder file

src/main/java/com/microsoft/graph/serializer/GsonFactory.java, src/test/java/com/microsoft/graph/serializer/DefaultSerializerTests.java
fixes #568 a bug where duration deserlization would fail because of quotes
=> - fixes #568: a bug where time duration deserialization would fail because of quotes

typesummary/app/gradle.properties, typesummary/gradle.properties
the gradle.properties for the typesummary project was not at the right place.
This lead to the JVM not being configured properly and running into heap exceptions.
The issue was detected on the beta SDK as it contains much more code
=> - moves the properties file to the right folder to apply configuration and avoid heap exceptions

Scripts/incrementMinorVersion.ps1
Linux runners require case sensitivity.
=> Fix README path

src/main/java/com/microsoft/graph/serializer/DefaultSerializer.java
This is a comparison using reference equality instead of value equality. Reference equality of boxed primitive types is usually not useful, as they are value objects, and it is bug-prone, as instances are cached for some values but not others.
=> Don't use reference equality on Integers

docs/upgrade-to-v3.md, gradle/dependencies.gradle, pom.xml
replaces #636
related https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/128
=> - upgrade ok http to latest

src/main/java/com/microsoft/graph/http/BaseCollectionRequest.java
Fixes #659
- Fix typo in BaseCollectionRequest setMaxRetries method, which caused the maximum redirects to be set instead of  maximum retries
=> Fix BaseCollectionRequest setMaxRetries method

src/main/java/com/microsoft/graph/http/GraphServiceException.java, src/main/java/com/microsoft/graph/requests/extensions/ChunkedUploadResult.java, src/test/java/com/microsoft/graph/http/GraphServiceExceptionTests.java
- fixes a bug where the errors would log sensitive payload information when not set to verbose
fixes #685
=> - fixes a bug where the errors would log sensitive payload information when not set to verbose

docs/upgrade-to-v3.md
As ChunckUploadProvider was renamed to LargeFileUploadTask and also changed the package name, I think it would be better to have both changes one after the other.
I also changed the ChunckUploadProvider mention under non-generated code topic.
=> updates the mention to the ChunkUploadProvider

.github/workflows/api-level-lint.yml, .github/workflows/codeql-analysis.yml
generation PRs don't trigger the worfklows anymore as they are created by a bot (and actions don't trigger when the trigger was started by a bot).
This PR adds the ability to manually trigger the actions.
We could, in a subsequent PR, add steps in the generation pipeline to trigger the actions "manually". https://github.com/marketplace/actions/workflow-dispatch
=> - adds worfkow dispatch trigger to codeQL and api level lint

gradle/dependencies.gradle
Kiota dependencies in core have been upgraded to 'api' meaning they are now visible/usable here. We can remove the Kiota components from here and use them through transitivity.
=> Remove implementations for Kiota Components

.github/workflows/codeql-analysis.yml
https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/troubleshooting-the-codeql-workflow#warning-git-checkout-head2-is-no-longer-necessary
github.com/controlplaneio/kubesec/issues/132
=> Code Ql update 

.github/policies/msgraph-sdk-java-branch-protection.yml
Capture current policy state so that we can make versioned changes to branch protection policies. This will enable policy history, auditing, review, standardization, and templatization. We will update policy in later PR.
We can ignore the rule that states: `At least one value under RequiredStatusChecks must be specified when RequiresStrictStatusChecks is true.` or `RequiresStrictStatusChecks must be true when specifying RequiredStatusChecks.` This is getting removed. This is getting removed.
* https://github.com/microsoft/GitOps.Branches/pull/73
* https://github.com/microsoft/GitOps.Branches/issues/72
This branch protection policy will not take effect until https://github.com/microsoftgraph/.github/blob/main/policies/branch-protection-sdks.yml has been removed.
=> chore: capture initial branch policy settings

.github/policies/msgraph-sdk-java-branch-protection.yml
* All dev and main branches must have policy
* Require status checks to pass before merging
* Require code owner approvals of all changes in main/master and dev branches
* Require re-approval after new commits
> **Note**: We must validate this PR after merge by opening another PR to make sure that the required status checks run as expected so that we don't introduce misconfigured blocking policy.
=> chore: update branch protection rules

src/main/java/com/microsoft/graph/serviceclient/GraphServiceClient.java
Remove BackingStoreFactory param from GraphServiceClient constructors. 
Also, change import statement for AzureIdentityAuthenticationProvider
com.microsoft.kiota.authentication.AzureIdentityAuthenticationProvider -> com.microsoft.graph.core.authentication.AzureIdentityAuthenticationProvider 
The Core implementation provides the correct hosts by utilizing the implementation of AzureIdentityAccessTokenProvider in Core.
=> V6 remove backing store param

CHANGELOG.md, README.md, gradle.properties, gradle/dependencies.gradle, src/main/java/com/microsoft/graph/info/Constants.java
Graph Core `3.1.3` contains the error deserialization bug fix to unblock customers.
=> Bumps Graph Core dependency version and update lib version for release

.github/workflows/codeql-analysis.yml
Disables caching seems to work following hints from https://docs.github.com/en/code-security/code-scanning/troubleshooting-code-scanning/no-source-code-seen-during-build
This seems to work for v1. Beta still throws the OutOfMemory error during the build step.
=> Fix failing CodeQL checks

.github/workflows/gradle-build.yml
This PR:
- Fixes failing `compare-packages` checks in https://github.com/microsoftgraph/msgraph-sdk-java/pull/2022
Context:
- Release workflow was [updated ](https://github.com/microsoftgraph/msgraph-sdk-java/blob/main/.github/workflows/preview-and-release.yml#L57)to upload build artifacts to workflow runs only when a tag is created by release-please.
- This changes `download-artifact` to use the latest successful run by fetching the latest tag name using GitHub CLI
=> Fix branch name to download previous release artifacts from

.github/workflows/preview-and-release.yml
Attempts to trigger Maven central release are now being triggered by PRs instead of tags by release-please e.g. https://github.com/microsoftgraph/msgraph-sdk-java/actions/runs/9361922743
Bug seems to have been introduced by https://github.com/microsoftgraph/msgraph-sdk-java/pull/2025
=> Fix bug in triggering maven central release workflow

.github/workflows/api-level-lint.yml, .github/workflows/gradle-build.yml
related https://www.sonatype.com/blog/maven-central-and-the-tragedy-of-the-commons
=> ci: adds missing gradle dependencies caching to CI

.github/workflows/validate-public-api-surface.yml
Minor tweak to remove validation comments etc from PRs that don't need the checks e.g. [release PR](https://github.com/microsoftgraph/msgraph-sdk-java/pull/2181#issuecomment-2387773439)
=> Limit API surface validation to generated files

.github/workflows/api-level-lint.yml, .github/workflows/gradle-build.yml, .github/workflows/preview-and-release.yml, build.gradle, scripts/copyFilesOnBuild.ps1
fixes https://github.com/microsoftgraph/msgraph-sdk-java/issues/2078
fixes https://github.com/microsoftgraph/msgraph-sdk-java/issues/1893
This PR includes the following changes.
- enables the javadoc task to ensure that javadocs are part of release task artifacts
- adds a step in CI/CD stages to move sources in the `/generated` folder up one folder so that the generated sources are in the correct package structure
Considerations.
As much as updating the generation pipeline to place the generated files in the correct package structure is a good idea, we have a number of hand writter files in the root path such as https://github.com/microsoftgraph/msgraph-sdk-java/pull/2298 that would be overwritten or replaced. The alternative would involve keeping a record of handwritten files and moving …
=> fix: resolve javadoc and source locations

src/main/java/com/microsoft/graph/serviceclient/GraphServiceClient.java
fixes https://github.com/microsoftgraph/msgraph-sdk-java/issues/2354
Fixes [#]2354(https://github.com/microsoftgraph/msgraph-sdk-java/issues/2354)
-Allows Us to Overide the default Base URL in use cases such as GCC customers
=> Added new constructor for GraphServiceClient
