microsoftgraph/msgraph-sdk-java

src/main/java/com/microsoft/graph/concurrency/ChunkedUploadResponseHandler.java, src/main/java/com/microsoft/graph/requests/extensions/ChunkedUploadRequest.java, src/main/java/com/microsoft/graph/requests/extensions/ChunkedUploadResult.java
=> fix raw type usage in ChunkedUploadResult

src/main/java/com/microsoft/graph/http/BaseRequest.java, src/main/java/com/microsoft/graph/http/BaseRequestBuilder.java, src/main/java/com/microsoft/graph/http/BaseStreamRequest.java, src/main/java/com/microsoft/graph/http/DefaultHttpProvider.java
Fixes around `BaseRequest`:
* unused imports
* raw type usage (#25 would be good when we can get round to it)
=> fix some unused imports and raw type usage

gradlew, gradlew.bat
Upgrade the `gradlew` and `gradlew.bat` files to match the 4.5.1 gradle release
=> Upgrade gradlew and gradlew.bat for gradle 4.5.1

src/main/java/com/microsoft/graph/concurrency/DefaultExecutors.java, src/main/java/com/microsoft/graph/concurrency/IExecutors.java, src/main/java/com/microsoft/graph/core/BaseClient.java, src/main/java/com/microsoft/graph/core/IBaseClient.java
Fixes # Fix for issue https://github.com/microsoftgraph/msgraph-sdk-java/issues/84
- Added a hook to shutdown background executor
-
=> Give the hook to shut down background executor gracefully

src/main/java/com/microsoft/graph/serializer/DefaultSerializer.java
Fixes #
Fix for - AdditionalDataManager was not getting populated for child objects while deserializing the json
Have added a function in DefaultSerializer class which gets called recursively to set additional data on Child objects as well
=> Deserializing additional data throughout the object hierarchy

src/test/java/com/microsoft/graph/concurrency/MockExecutors.java, src/test/java/com/microsoft/graph/core/MockBaseClient.java, src/test/java/com/microsoft/graph/requests/extensions/GraphServiceClientTest.java
Implemented interface functions shutdownBackgroundExecutors, shutdown and shutdownBackgroundExecutors of MockExecutors.java, MockBaseClient.java and GraphServiceClientTest.java. Built successfully.
=> Abstract funcs fix

src/main/java/com/microsoft/graph/http/DefaultHttpProvider.java
Fixing issue https://github.com/microsoftgraph/msgraph-sdk-java/issues/95 by giving UTF-8 as parameter to getBytes.
=> Utf issue fix

src/main/java/com/microsoft/graph/http/GraphServiceException.java
Fixes # https://github.com/microsoftgraph/msgraph-sdk-java/issues/107
GraphServiceException encapsulates a bit too much?
=> get HTTP status response code in GraphServiceException

src/main/java/com/microsoft/graph/serializer/EnumSetSerializer.java
Fixes #37 iterator part.
Fix - Using wildcard <?> with iterator.
**Changes proposed in this pull request**
Removing raw type iterator and changing it to parameterized type as it is possible that future versions of java disallow the use of raw types.
=> Fixes raw type iterator warning

build.gradle, gradle.properties
Adding mavenCentral, change in destination repo url and input format of credentials for sonatype.
=> Changes done for publishing to Maven Central in SNAPSHOT versioning

build.gradle, gradle.properties
Fixes #67 Publishes to maven central's snapshot repository for use in maven projects.
=> Publishes to Maven central.

build.gradle
Fixes build fail because of maven central.
=> Maven central build fix

README.md, build.gradle, gradle.properties
-Changed build.gradle to publish in mavenCentral
-Edited Readme doc to include sdk in maven
-Added required properties in gradle.properties
=> Changes to publish to maven central and readme edit.

src/main/java/com/microsoft/graph/http/BaseCollectionRequest.java
Fixes #66 
-Changed T2 to BodyType so that naming doesn't have conflict with class level T2
-Edited comment with BodyType
-In some scenarios Action use different body than collection item, by which post of BaseCollectionRequest gets different parameter other than T2 and different body.
Previous PR - https://github.com/microsoftgraph/msgraph-sdk-java/pull/116
=> Type hiding warning fix

README.md
Fixes Readme-
- Changed jcenter{ url "https://dl.bintray.com/microsoftgraph/Maven" } in Readme to jcenter().
- Increased version in Readme to be used to 0.3.+
=> fix readme jcenter()

README.md, gradle.properties
1. Fix MavenRepoURL
2. Upgrade maven minor version for next release
3. Update readme to reflect latest release
=> Fix mavenRepoURL and upgrade maven minor version

build.gradle
- Enable/Disable signing tasks through enableSigning variable in local.properties
=> Enable signing using local.properties

build.gradle
- Loading of signing signing.secretKeyRingFile, signing.keyId, signing.password and enableSigning from local.properties for publishing to maven central release.
=> Load credentials and signing info from local.properties

build.gradle, gradle.properties
- Upload to bintray snapshot repo using command 
gradlew publishSnapshotPublicationToMaven3Repository
- Link to repo: http://oss.jfrog.org/oss-snapshot-local/com/microsoft/graph/microsoft-graph/
=> Bintray snapshot uploader task

build.gradle
- Changed username of bintray's snapshot repo to lowercase
=> Changed bintray snapshot repo's username to lowercase.

src/main/java/com/microsoft/graph/http/GraphServiceException.java
Fixes #149 
-  Added function to access the response message of HTTP request.
=> Function to access response message

src/main/java/com/microsoft/graph/http/UrlConnection.java
Fixes #166
- added default connection and read timeout set to 30s
=> #166 - added default connect and read timeout to UrlConnection

src/test/java/com/microsoft/graph/functional/CalendarTests.java, src/test/java/com/microsoft/graph/functional/UserTests.java
- Added more tests related to user and calendar.
=> Enchanced tests

src/main/java/com/microsoft/graph/models/extensions/TimeOfDay.java, src/main/java/com/microsoft/graph/serializer/GsonFactory.java, src/test/java/com/microsoft/graph/serializer/TimeOfDayTests.java
Addresses https://github.com/microsoftgraph/msgraph-sdk-java/issues/168
=> Fix for #168 TimeOfDay deseralization

gradle.properties, src/main/java/com/microsoft/graph/core/Constants.java
Incrementing SDK version to 1.0.2 for binary release.
=> Increment SDK version for release

README.md
Update readme file to use 1.0.2 sdk version.
=> Update readme file to reflect current released sdk binary

src/main/java/com/microsoft/graph/serializer/DefaultSerializer.java, src/test/java/com/microsoft/graph/serializer/AdditionalDataTests.java
Fixes : Corrects deserialization of Hashmap's contents along with their respective additionalDataManager's contents.
- pass json of corresponding item,json pair in childAdditionalDataManager.setAdditionalData and setChildAdditionalData.
- tests to check serialization and deserialization of hashmap.
=> Hashmap deserialization fix and its tests

src/main/java/com/microsoft/graph/http/CustomRequest.java, src/test/java/com/microsoft/graph/functional/CustomRequestTests.java
Fixes #185 
- Put functionality added in Custom request.
=> Put added in custom request.

README.md
- Update Version 1.2.0 in readme
=> Updated version 1.2.0 in readme

README.md
- Updated readme version to 1.3.0
=> Updated readme version 1.3.0

src/main/java/com/microsoft/graph/http/GraphServiceException.java, src/test/java/com/microsoft/graph/http/GraphServiceExceptionTests.java
Fixes #241 
- Null check when resposne body is null in error status code.
- Test for null response body
=> Null check on empty graph error body

README.md
- Version updated to 1.4.0 for new release.
=> Updated version to 1.4.0

src/main/java/com/microsoft/graph/concurrency/ChunkedUploadProvider.java, src/main/java/com/microsoft/graph/requests/extensions/ChunkedUploadRequest.java, src/test/java/com/microsoft/graph/functional/OneDriveTests.java
Fixes #211
- Fixes ChunkedUpload limit due to the type int, see #211
- Please merge also https://github.com/microsoftgraph/msgraph-sdk-android/pull/107
=> microsoftgraph/msgraph-sdk-java#211 fix ChunkedUpload limit

README.md
=> Update version to 1.5.0 in README

src/main/java/com/microsoft/graph/logger/DefaultLogger.java, src/test/java/com/microsoft/graph/logger/DefaultLoggerTests.java
Fixes #239
- Changed default logging level to ERROR (initially was DEBUG).
=> Changed the current logging level to ERROR.

src/main/java/com/microsoft/graph/serializer/CalendarSerializer.java, src/test/java/com/microsoft/graph/serializer/CalendarSerializerTests.java
- Enhanced CalendarSerializer to deserialize dates with positive and negative offsets along in various formats
- Fixed bugs while deserializing date with millisecond and negative timezone offset
- Added unit tests for all cases of deserialization
- https://en.wikipedia.org/wiki/ISO_8601
=> Enhanced CalendarSerializer and fixed bugs in deserialization

src/main/java/com/microsoft/graph/concurrency/ChunkedUploadProvider.java
Fixes #
Upload large files fix - Changed readSoFar type from int to long
=> Upload large files fix

.github/dependabot.yml
=> - adds dependabot to repo

.github/workflows/create-v1.0-pull-request.yml
- updates reviewers and assignees for codegen PRs
=> - updates reviewers and assignees for codegen PRs

README.md
=> - fixes #407: updates recommended install version to match latest

.github/workflows/conflicting-pr-label.yml
=> - adds a workflow to handle conflicting PRs automatically

.github/workflows/codeql-analysis.yml
=> - adds code scanning

README.md
cleaning up old branches, this one never got PRed so I'd like feedback to whether we should merge it or delete it
=> Updated readme with auth repos links

README.md
- fixes gradle installation indications
=> - fixes gradle installation indications

Scripts/getLatestVersion.ps1, Scripts/validateMavenVersion.ps1
- adds missing scritps for autoamted github release (copied from java core)
- fixes #434
=> - fixes #434 : adds github release scripts for automated release creation

build.gradle
Sorry @MIchaelMainer I forgot to replicate changes all the way at the bottom...
=> - removes a task injection that was forgotten in previous updates

src/main/java/com/microsoft/graph/serializer/DefaultSerializer.java
=> - fixes an issue where responses headers would be serialized with subsequent requests

src/main/java/com/microsoft/graph/serializer/DefaultSerializer.java, src/test/java/com/microsoft/graph/serializer/AdditionalDataTests.java
=> - fixes a bug where additional properties for upload sessions would not be send to the service

build.gradle, src/main/java/com/microsoft/graph/http/BaseRequest.java, src/test/java/com/microsoft/graph/http/BaseCollectionPageTests.java, src/test/java/com/microsoft/graph/http/BaseCollectionRequestTests.java, src/test/java/com/microsoft/graph/http/BaseRequestBuilderTests.java, src/test/java/com/microsoft/graph/http/BaseRequestTests.java, src/test/java/com/microsoft/graph/http/BaseStreamRequestTests.java
Fixes #328
Fixes #306 
Fixes #213 
Fixes #258
- removes jersey server dependency as we only used one class from it and it has licensing implications (CDDL)
- adds ok http3 (aligned with core)
- replaces the only call to the lib (url builder)
- fixes nonsense unit tests
-
=> - removes jersey server to reduce depencies and fix licensing

src/main/java/com/microsoft/graph/http/CoreHttpProvider.java, src/test/java/com/microsoft/graph/functional/UserTests.java
Fixes #176
Closes #177
Depends on #202 
-
-
=> - fixes a bug where uploading a profile photo would result in an invalid cast exception

src/test/java/com/microsoft/graph/functional/OneDriveTests.java
=> - adds a unit test for ODSP file download with custom request

src/main/java/com/microsoft/graph/serializer/DefaultSerializer.java, src/test/java/com/microsoft/graph/serializer/AdditionalDataTests.java
=> - fixes a bug where additional properties would not be attached at the right level

src/main/java/com/microsoft/graph/core/Constants.java, src/main/java/com/microsoft/graph/http/CoreHttpProvider.java, src/test/java/com/microsoft/graph/functional/OneDriveTests.java
=> - fixes a bug where downloading json files from onedrive would cause a cast exception

README.md, docs/proguard-rules.txt
=> - fixes #462 adds sample proguard rules

build.gradle
fixes #297
related https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/77
=> - turns on automatic module for JPMS

src/main/java/com/microsoft/graph/requests/extensions/IMessageRequestBuilder.java, src/main/java/com/microsoft/graph/requests/extensions/MessageRequestBuilder.java
=> - fixes a regression where the content method would be missing for message

src/main/java/com/microsoft/graph/http/CoreHttpProvider.java, src/main/java/com/microsoft/graph/http/DefaultHttpProvider.java, src/main/java/com/microsoft/graph/http/GraphServiceException.java, src/test/java/com/microsoft/graph/http/CoreHttpProviderTests.java, src/test/java/com/microsoft/graph/http/DefaultHttpProviderTests.java
Fixes #565
The changes fix the issue which occurs when the body of the response is empty.
-
-
=> Issue#565: fixed the iterator issue

Scripts/getLatestVersion.ps1
revert script deletion from #571
=> - restores wrongfully deleted script

Scripts/incrementMinorVersion.ps1
- adds improvements from core pull request review for version increment script
https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/89
=> - applies recommendations from core PR

src/main/java/com/microsoft/graph/serializer/EnumSetSerializer.java, src/main/java/com/microsoft/graph/serializer/GsonFactory.java, src/test/java/com/microsoft/graph/serializer/DefaultSerializerTests.java
=> - fixes a bug where enum set properties would not be serialized properly

.github/CODEOWNERS
- adds codeowners so reviewers are added automatically
=> - adds code owners to avoid having to add PR reviewers manually anymore

src/main/java/com/microsoft/graph/serializer/EnumSetSerializer.java
@MIchaelMainer @zengin FYI this pull reuqest was submitted from codespaces :D
=> - adds missing param for serializer logger

src/main/java/com/microsoft/graph/http/BaseCollectionPage.java
=> - fixes an issue where receiving no content responses for collections would cause an NPE

CODE_OF_CONDUCT.md, SECURITY.md
- adds a security manifest to follow MS open source repos standards
=> - adds security manifest to the repo

CONTRIBUTING.md, README.md
related https://github.com/microsoftgraph/msgraph-sdk-java-core/issues/75
=> - removes wiki links from the markdown documents to prepare for wiki disable

docs/upgrade-to-v3.md
- adds an upgrade guide to sdk v3
=> - adds a first version of the upgrade guide for v3

README.md, gradle.properties, gradle/dependencies.gradle, src/main/java/com/microsoft/graph/info/Constants.java, typesummary/app/build.gradle
- major bumps the version in prepration for preview release
=> - major bump

src/test/java/com/microsoft/graph/functional/OutlookTests.java
related https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/125
=> - adds a unit test for end to end inheritance testing

docs/upgrade-to-v3.md
- adds delta upgrade instructions
=> - adds upgrade guidelines for delta

android/gradle/wrapper/gradle-wrapper.properties, gradle/wrapper/gradle-wrapper.properties, typesummary/gradle/wrapper/gradle-wrapper.properties
https://docs.gradle.org/current/release-notes.html
=> - upgrades gradle wrapper to 6.8.1

build.gradle, pom.xml, typesummary/app/build.gradle
related https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/140
=> - updates reference to core lib

src/main/java/com/microsoft/graph/http/GraphError.java, src/test/java/com/microsoft/graph/http/GraphErrorTests.java
=> - fixes a bug where the SDK would be expecting a different casing tahn the service for error codes

README.md, build.gradle, gradle.properties, typesummary/app/build.gradle
partial https://github.com/microsoftgraph/msgraph-sdk-java-core/issues/131
=> - removes bintray from repo in anticipation for service sunset

gradle/dependencies.gradle
=> - minor dependencies upgrade

.github/workflows/create-v1.0-pull-request.yml
- removes darrel from generation comment to save him notifications
=> - removes darrel from generation comments to save him notifications

android/build.gradle
- suppresses false negative rule
reflection of https://github.com/MicrosoftGraph/msgraph-beta-sdk-java/pulls/80
=> - suppresses a rule to avoid getting false positives because of metadata

README.md, src/main/java/com/microsoft/graph/requests/GraphServiceClient.java
- fixes an issue where clients would get a type safety warning because of a missing generic type
=> - fixes a bug where clients would get a warning because of a missing generic type

Scripts/incrementMinorVersion.ps1
reflexion of https://github.com/microsoftgraph/msgraph-beta-sdk-java/pull/108
=>  - aligns increment version script with beta

.azure-pipelines/buildAndPackage.yml, .azure-pipelines/templates/alert-failure.yml, .azure-pipelines/templates/build/checkout-and-credscan.yml, .azure-pipelines/templates/secure-files.yml, .azure-pipelines/templates/version-and-release.yml
- Name fixes
- Missing Parenthesis Added
- Removed Alert Failure
=> fixed stage names and git connection,removed alert failure

gradle/dependencies.gradle, pom.xml
microsoft-graph-core update 2.0.8 to 2.0.9
=> microsoft-graph-core update to 2.0.9

.github/workflows/create-v1.0-pull-request.yml
Queue the workflows when dependabot creates a pr.
=> Queue Workflows on pr creation

.github/workflows/create-v1.0-pull-request.yml
See: https://github.com/microsoftgraph/msgraph-beta-sdk-java/pull/175
=> Switch to Personal Token

.github/workflows/gradle-build.yml
Add job to Build CI workflow that handles diff generation.
=> Compare Pkgs and Upload Diff

docs/upgrade-to-v3.md
Fixes 995
Fixes to the example code for batches in the v3 migration guide
=> fixing example code for batches

.github/workflows/gradle-build.yml
Noticed that the diff report was not being uploaded for this repo. Added the always condition to be in line with the Beta repo, thus it should now always upload a diff report.
Fixes #
-
-
=> Updating Build action

CHANGELOG.md, README.md, gradle.properties, gradle/dependencies.gradle, pom.xml, src/main/java/com/microsoft/graph/info/Constants.java
https://github.com/microsoftgraph/msgraph-sdk-java-core/issues/483
=> Take dependency on graph-core 2.0.12

CHANGELOG.md
Fix the changelog for version 5.22.0 release.
=> Fix 5.22.0 changelog

src/main/java/com/microsoft/graph/requests/GraphServiceClient.java
Hotfix for 83031 using BaseClient.Java.tt update: 
https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/811
=> Updated GraphServiceClient

gradle/dependencies.gradle
Add core 3.0 dependency snapshot
=> Add Core 3.0 Dependency snapshot

.github/workflows/api-level-lint.yml, .github/workflows/codeql-analysis.yml, .github/workflows/gradle-build.yml
Signed-off-by: Vincent Biret <vibiret@microsoft.com>
=> - fixes triggers for preview version

src/main/java/com/microsoft/serviceClient/GraphServiceClient.java
=> GraphServiceClient param annotations

.github/workflows/gradle-build.yml
=> Update PkgDiff for Kiota Branches

src/main/java/com/microsoft/serviceClient/GraphServiceClient.java
=> gradle 8.1

src/main/java/com/microsoft/serviceClient/GraphServiceClient.java
Implements IBaseClient, this is in line with dotNet and will help going forward with batch requests.
=> Update Graph Service Client to use IbaseClient

gradle/dependencies.gradle, src/main/java/com/microsoft/serviceClient/GraphServiceClient.java
adds the me() path to GraphServiceClient using a userItemRequestBuilder
=> add token to enable skip /me generation

CHANGELOG.md, android/build.gradle, gradle/dependencies.gradle, pom.xml
=> Tooling bumps v6

README.md, gradle.properties, gradle/dependencies.gradle, src/main/java/com/microsoft/graph/info/Constants.java
Bumps to 6.0.1
Depends on https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/1412
=> bump to version 6.0.1 to clear up possible dependency misalignment

.github/workflows/git-release.yml
Add permission to create release
=> Git Release permissions

CHANGELOG.md, gradle.properties, gradle/dependencies.gradle, src/main/java/com/microsoft/graph/info/Constants.java
=> - fixes a dependencies misalignment issue

release-please-config.json
ci: update bootstrap SHA
- Switch to using `simple` strategy in release management. Avoids extra snapshot PR being created. See #1945
=> ci: switch to using simple release strategy to avoid extra SNAPSHOT PR.

.github/workflows/auto-merge-dependabot.yml, .github/workflows/conflicting-pr-label.yml, .github/workflows/gradle-build.yml
=> - fixes trigger definition for CI

.github/workflows/preview-and-release.yml
part of https://github.com/microsoftgraph/msgraph-sdk-java/issues/1978
=> Trigger maven releases on tag creation

.github/policies/msgraph-sdk-java-branch-protection.yml, .github/release-please.yml, .github/workflows/api-level-lint.yml, .github/workflows/auto-merge-dependabot.yml, .github/workflows/codeql-analysis.yml, .github/workflows/conflicting-pr-label.yml, .github/workflows/gradle-build.yml, .github/workflows/preview-and-release.yml
@baywet ready for `main` to be set as default.
=> Change default branch to main

.github/workflows/preview-and-release.yml
fix remaining work in https://github.com/microsoftgraph/msgraph-sdk-java/issues/1978#issuecomment-2127366805
closes https://github.com/microsoftgraph/msgraph-sdk-java/issues/1978
=> Trigger maven releases on tags by release-please only

.github/dependabot.yml
=> Prevent duplicate dependabot PRs

docs/upgrade-to-v6.md
=> docs: fixes the custom authentication provider example in upgrade documentation

.github/workflows/gradle-build.yml, .github/workflows/preview-and-release.yml, .secrets.baseline
- Update workflows to fail when new secrets are detected
- Updates baseline to ignore `kiota-lock` and generated files
=> Update secrets scanning baseline and workflow

.github/workflows/preview-and-release.yml
Fixes failing runs: https://github.com/microsoftgraph/msgraph-sdk-java/actions/runs/10371932287
=> Fix artifact Id in release validation workflow

.github/workflows/validate-public-api-surface.yml
closes https://github.com/microsoftgraph/msgraph-sdk-java/issues/2138
=> Add API surface validation workflow

android/build.gradle
unblocks https://github.com/microsoftgraph/msgraph-sdk-java/pull/2181
=> Update Android Gradle build tools

README.md
closes https://github.com/microsoftgraph/msgraph-sdk-java/issues/2270
=> Update azure-identity version in README.md

gradle/dependencies.gradle, src/main/java/com/microsoft/graph/models/ChangeNotification.java, src/main/java/com/microsoft/graph/models/ChangeNotificationCollection.java, src/main/java/com/microsoft/graph/models/ChangeNotificationCollectionResponse.java, src/main/java/com/microsoft/graph/models/ChangeNotificationEncryptedContent.java, src/main/java/com/microsoft/graph/models/ChangeType.java, src/main/java/com/microsoft/graph/models/LifecycleEventType.java, src/main/java/com/microsoft/graph/models/ResourceData.java
depends on https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/1837
closes https://github.com/microsoftgraph/msgraph-sdk-java/issues/1891
=> feat: add ChangeNotification models

.azure-pipelines/ci-build.yml, .github/workflows/preview-and-release.yml, build.gradle, scripts/validatePackageContents.ps1, scripts/zipPackageContent.ps1
related https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/1921
to enable creation and testing of the pipeline
=> ci: draft migration to ESRP release
